var tableauQuestion = [
    {   question : "Se você estiver dirigindo a 80 kmh, e você se aproxima de uma área residencial, isso significa que",
        propositionA : "Você precisará acelerar a frente",
        propositionB : "Você pode acelerar enquanto não houver outros carros",
        propositionC : "Você terá que diminuir a velocidade",
        propositionD : "Você pode manter sua velocidade",
        reponse : "C"},
		
    {   question : "Ao virar à esquerda sobre uma luz verde, você vê que um pedestre está no cruzamento. Quem tem o direito de passagem?",
        propositionA : "O pedestre, porque eles podem atravessar a estrada com qualquer luz",
        propositionB : "Seu veículo porque a luz é verde",
        propositionC : "O pedestriano, porque ele / ela atravessa com a luz verde",
        propositionD : "Seu veículo, porque os veículos são sempre entregues",
        reponse : "C"},
		
    {   question : "A menos que publicado, a velocidade máxima em uma área residencial é ____ kmh.",
        propositionA : "50",
        propositionB : "55",
        propositionC : "65",
        propositionD : "70",
        reponse : "A"},
	
	{   question : "Antes de cada mudança de faixa, você deveria..",
        propositionA : "Verifique seus espelhos",
        propositionB : "Verifique seus pontos cegos",
        propositionC : "Sinalize suas intenções",
        propositionD : "Todos os itens acima",
        reponse : "D"},
		
	{   question : "Qual nível de álcool no sangue é classificado como dirigindo enquanto está intoxicado?",
        propositionA : "0.05%",
        propositionB : "0.18%",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "C"},
		
	{   question : "Você deve puxar e parar até que qualquer veículo de emergência com uma sirene tenha passado, a menos que:",
        propositionA : "Você está com pressa",
        propositionB : "Há espaço suficiente para eles em uma faixa não inferior",
        propositionC : "Você está numa zona escolar",
        propositionD : "Você está  numa interseção",
        reponse : "D"},
	
	{   question : "O direito de passagem deve ser cedido aos veículos de emergência",
        propositionA : "Em todos os momentos",
        propositionB : "Luzes vermelhas, azuis ou brancas intermitentes",
        propositionC : "Usando uma sirene ou piscando luzes vermelhas, azuis ou brancas",
        propositionD : "Usando uma sirene",
        reponse : "C"},
		
	{   question : "Qual das seguintes condições é permitida ao passar por outro veículo?",
        propositionA : "Seguindo de perto",
        propositionB : "Deixando a estrada principal viajada",
        propositionC : "Dirigindo no lado oposto da estrada",
        propositionD : "Excedendo o limite de velocidade",
        reponse : "C"},
		
	{   question : "Você está dirigindo em uma auto-estrada com um limite de velocidade de 110 kmh. A maior parte do tráfego está viajando a 120 mph, então você deve dirigir não mais rápido do que",
        propositionA : "80 kmh",
        propositionB : "40 kmh",
        propositionC : "50 kmh",
        propositionD : "110 kmh",
        reponse : "D"},
		
	{   question : "Ao ser passado por outro veículo, é importante NÃO",
        propositionA : "Abrandar",
        propositionB : "Verifique seus espelhos",
        propositionC : "Olhe para o outro condutor",
        propositionD : "Acelerar",
        reponse : "D"},
]
